<?php
/**
 * Generated by PHPUnit_SkeletonGenerator on 2012-07-04 at 14:57:34.
 */
use Parser\TestObjects\TestObjectCollection;

use Parser\TestObjects\TestObject;

class Parser_Tests_ArrayToCollectionTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var Parser\ArrayToCollection
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Parser\ArrayToCollection;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Parser\ArrayToCollection::getOutput
     */
    public function testGetOutput()
    {   
        $testObject = new TestObject();
        $testObject
            ->setFirstProperty(1)
            ->setSecondProperty(2);
        
        $testObjectTwo = new TestObject();
        $testObjectTwo
            ->setFirstProperty(3)
            ->setSecondProperty(4);
        
        $collection = new TestObjectCollection();
        $collection
            ->addItem($testObject)
            ->addItem($testObjectTwo);
        
        $testArray = array(
            array(
                    'first_property'  => 1,
                    'second_property' => 2
            ),
            array(
                    'first_property'  => 3,
                    'second_property' => 4
            )
        );
        
        $actual = $this->object->getOutput($testArray, array(
                    'class_name' => '\\Parser\\TestObjects\\TestObject'
                ));
        
        $this->assertEquals($collection, $actual);
    }
}
