<?php

/**
 * Generated by PHPUnit_SkeletonGenerator on 2012-07-04 at 14:43:25.
 */
class Parser_Tests_CamelCaseTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var Parser\CamelCase
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Parser\CamelCase;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Parser\CamelCase::getOutput
     */
    public function testGetOutput()
    {
        $this->assertEquals('CamelCaseTestString', $this->object->getOutput('camel_case_test_string'));
    }
}
