<?php

/**
 * Generated by PHPUnit_SkeletonGenerator on 2012-07-04 at 14:43:25.
 */
class Parser_Tests_ParserTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var Parser\Parser
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Parser\Parser;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Parser\Parser::get
     */
    public function testGetOutput()
    {
        $parser = $this->object->get('ArrayToObject');
        
        $this->assertTrue($parser instanceof Parser\ArrayToObject);
    }
}
